name: Daily Vocabulary Email

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM every day (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-vocabulary-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: |
        npm install nodemailer csv-parser dotenv
        
    - name: Send vocabulary email
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}  # Your Zoho email, stored as GitHub Secret
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}  # Your Zoho app password, stored as GitHub Secret
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}  # The recipient email, stored as GitHub Secret
      run: node index.js  # Ensure you have a script to send the email

    - name: Update word database
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add vocabulary_database.csv
        git commit -m "Update word database" || echo "No changes to commit"
        git push
