name: Daily Vocabulary Email

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-vocabulary-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sendgrid pandas
        
    - name: Send vocabulary email
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      run: python send_vocabulary_email.py
      
    - name: Update word database
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add words_database.csv
        git commit -m "Update word database" || echo "No changes to commit"
        git push
